name: Install Roblox

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Roblox Installer
        run: |
          Invoke-WebRequest -Uri "https://setup.rbxcdn.com/RobloxPlayerInstaller.exe" -OutFile "RobloxPlayerInstaller.exe"

      - name: Install Roblox
        run: |
          Start-Process -FilePath "RobloxPlayerInstaller.exe" -ArgumentList "-quiet" -NoNewWindow -Wait

      - name: Find Installed Files
        run: |
          Compress-Archive -Path "$env:LOCALAPPDATA\Roblox\*" -DestinationPath "RobloxClient.zip"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RobloxClient
          path: RobloxClient.zip

      - name: Expose API Token in HTML (for GitHub Pages)
        run: |
          echo "<script>window.apiToken = '${{ secrets.api }}';</script>" > api.js
          
      - name: Commit API Token to GitHub Pages Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          git add api.js
          git commit -m "Expose API Token for Frontend"
          git push origin gh-pages --force
