name: Install Roblox

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Roblox Installer
        run: |
          Invoke-WebRequest -Uri "https://setup.rbxcdn.com/RobloxPlayerInstaller.exe" -OutFile "RobloxPlayerInstaller.exe"

      - name: Install Roblox
        run: |
          Start-Process -FilePath "RobloxPlayerInstaller.exe" -ArgumentList "-quiet" -NoNewWindow -Wait

      - name: Find Installed Roblox Version Folder
        id: find_roblox
        run: |
          # Define the root directory for Roblox installations
          $RobloxRoot = "$env:LOCALAPPDATA\Roblox"
          
          # Recursively search for RobloxPlayerBeta.exe
          $RobloxExe = Get-ChildItem -Path $RobloxRoot -Recurse -Filter "RobloxPlayerBeta.exe" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1

          if ($null -eq $RobloxExe) {
              Write-Error "RobloxPlayerBeta.exe not found in $RobloxRoot"
              exit 1
          }

          $RobloxExePath = $RobloxExe.FullName
          $RobloxFolder = $RobloxExe.DirectoryName

          echo "Roblox EXE Path: $RobloxExePath"
          echo "ROBLOX_EXE_PATH=$RobloxExePath" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ROBLOX_FOLDER=$RobloxFolder" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create Windows Shortcut
        run: |
          if ($env:ROBLOX_EXE_PATH) {
              $WScriptShell = New-Object -ComObject WScript.Shell
              # Create the shortcut in the same folder as the Roblox executable
              $Shortcut = $WScriptShell.CreateShortcut("$env:ROBLOX_FOLDER\Roblox Install.lnk")
              $Shortcut.TargetPath = "$env:ROBLOX_EXE_PATH"
              $Shortcut.Save()
          } else {
              Write-Error "Roblox executable path not found."
              exit 1
          }
        shell: powershell

      - name: Package Installed Roblox into ZIP
        run: |
          if (Test-Path $env:ROBLOX_FOLDER) {
              Compress-Archive -Path "$env:ROBLOX_FOLDER\*" -DestinationPath "RobloxClient.zip"
          } else {
              Write-Error "Roblox folder not found at $env:ROBLOX_FOLDER"
              exit 1
          }

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxClient
          path: RobloxClient.zip
